=== Cienvariables/XML/Basic XSLT/books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="biblioteca">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="libro" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="libro">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element ref="autor"/>
        <xs:element ref="fechaPublicacion"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="autor">
    <xs:complexType mixed="true">
      <xs:attribute name="fechaNacimiento" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="fechaPublicacion">
    <xs:complexType>
      <xs:attribute name="año" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Cienvariables/XML/Basic XSLT/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="books.xslt"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="books.xsd">
  <libro>
    <titulo>La vida está en otra parte</titulo>
    <autor>Milan Kundera</autor>
    <fechaPublicacion año="1973"/>
  </libro>
  <libro>
    <titulo>Pantaleón y las visitadoras</titulo>
    <autor fechaNacimiento="28/03/1936">Mario Vargas Llosa</autor>
    <fechaPublicacion año="1973"/>
  </libro>
  <libro>
    <titulo>Conversación en la catedral</titulo>
    <autor fechaNacimiento="28/03/1936">Mario Vargas Llosa</autor>
    <fechaPublicacion año="1969"/>
  </libro>
</biblioteca>

<!-- Crear un XSL que muestre el título y los autores de cada libro, utilizando como template el elemento
“libro”. Tal como se muestra en la siguiente figura. -->
